[2024-03-04 15:06:05,376] 96 werkzeug -WARNING  * Debugger is active!
[2024-03-04 15:06:05,381] 96 werkzeug -INFO  * Debugger PIN: 274-803-487
[2024-03-04 15:06:06,464] 73 root -INFO Data Frame Gathered
[2024-03-04 15:06:06,699] 96 werkzeug -INFO 127.0.0.1 - - [04/Mar/2024 15:06:06] "[35m[1mPOST / HTTP/1.1[0m" 500 -
[2024-03-04 15:06:06,703] 96 werkzeug -ERROR Error on request:
Traceback (most recent call last):
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\werkzeug\debug\__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\flask-3.0.2-py3.8.egg\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\flask-3.0.2-py3.8.egg\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\flask-3.0.2-py3.8.egg\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\flask-3.0.2-py3.8.egg\flask\app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\flask-3.0.2-py3.8.egg\flask\app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\flask-3.0.2-py3.8.egg\flask\app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'predict_datapoint' did not return a valid response. The function either returned None or ended without a return statement.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\werkzeug\serving.py", line 325, in execute
    for data in application_iter:
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\werkzeug\debug\__init__.py", line 365, in debug_application
    environ["wsgi.errors"].write("".join(tb.render_traceback_text()))
OSError: [WinError 6] The handle is invalid
[2024-03-04 15:06:06,715] 96 werkzeug -INFO 127.0.0.1 - - [04/Mar/2024 15:06:06] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
[2024-03-04 15:06:06,718] 96 werkzeug -INFO 127.0.0.1 - - [04/Mar/2024 15:06:06] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
[2024-03-04 15:06:06,763] 96 werkzeug -INFO 127.0.0.1 - - [04/Mar/2024 15:06:06] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
[2024-03-04 15:06:06,802] 96 werkzeug -INFO 127.0.0.1 - - [04/Mar/2024 15:06:06] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
[2024-03-04 15:06:21,827] 73 root -INFO Data Frame Gathered
[2024-03-04 15:06:21,902] 96 werkzeug -INFO 127.0.0.1 - - [04/Mar/2024 15:06:21] "POST / HTTP/1.1" 200 -
[2024-03-04 15:06:21,940] 96 werkzeug -INFO 127.0.0.1 - - [04/Mar/2024 15:06:21] "GET /static/Hourglass/1.png HTTP/1.1" 200 -
[2024-03-04 15:06:21,941] 96 werkzeug -INFO 127.0.0.1 - - [04/Mar/2024 15:06:21] "GET /static/Hourglass/2.jpg HTTP/1.1" 200 -
[2024-03-04 15:06:21,942] 96 werkzeug -INFO 127.0.0.1 - - [04/Mar/2024 15:06:21] "GET /static/Hourglass/3.jpg HTTP/1.1" 200 -
[2024-03-04 15:06:21,943] 96 werkzeug -INFO 127.0.0.1 - - [04/Mar/2024 15:06:21] "GET /static/Hourglass/4.png HTTP/1.1" 200 -
[2024-03-04 15:07:04,265] 96 werkzeug -INFO  * Detected change in 'd:\\DevOps\\Project\\BE Project\\Outfit Recommendation\\app.py', reloading
